version: 0.0
os: linux
files:
  - source: /target/API-0.0.1
    destination: //opt/tomcat/webapps/data-sharing-manager
hooks:
  BeforeInstall:
    - location: cleanup
      timeout: 300
      runas: root
