# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/assign-uprn',
                'doc_host': 'https://joeldn.srht.site',
                'git_url': 'https://git.sr.ht/~joeldn/assign-uprn',
                'lib_path': 'assign_uprn'},
  'syms': { 'assign_uprn.api_calls': { 'assign_uprn.api_calls._secrets': ('api_calls.html#_secrets', 'assign_uprn/api_calls.py'),
                                       'assign_uprn.api_calls.address_search': ( 'api_calls.html#address_search',
                                                                                 'assign_uprn/api_calls.py'),
                                       'assign_uprn.api_calls.download': ('api_calls.html#download', 'assign_uprn/api_calls.py'),
                                       'assign_uprn.api_calls.upload': ('api_calls.html#upload', 'assign_uprn/api_calls.py')},
            'assign_uprn.core': {'assign_uprn.core.foo': ('core.html#foo', 'assign_uprn/core.py')}}}
